### ISSUE TITLE
Plugin fails to evaluate the configuration with Cypress 11

### ISSUE THREAD

**Issue by arneevertsson** [mbolotov/intellij-cypress#110]
**Describe the bug**
Running tests by clicking the gutter icon tries to run it as a Node.js run config, which fails.

**Versions**:
- Plugin: 3.5
- IDE: IntelliJ IDEA 2022.2.2 (Ultimate Edition)
- OS: MacOS

```
/usr/local/bin/node ....cy.js
...cy.js:3
describe("...", function ()
^

ReferenceError: describe is not defined
    at Object.<anonymous> (...cy.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Module._load (node:internal/modules/cjs/loader:838:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:18:47

Node.js v18.8.0

Process finished with exit code 1

```

**Comment by mbolotov** [comment]
Please make sure your cypress config selects this test for execution. 
Can you run it successfully from the command line?
Also, the plugin adds a cypress icon for every spec file that is selected by the cypress configuration:
![image](https://user-images.githubusercontent.com/19785715/201302090-3149dff9-6b2f-45e7-8716-8c2d251eb22f.png)
Do you see it for your spec file?

**Comment by arneevertsson** [comment]
What does it mean "cypress config selects this test"? My cypress.config.js contains nothing about selecting tests.

I can run the test from the command line, both with the Cypress ui and without it.

The gutter icon "cy" is not visible.

**Comment by mbolotov** [comment]
Cypress can run test that are matched by `specPattern` property of the cypress configuration (or `testFiles` in Cypress version < 10).
If you don't specify this value explicitly, Cypress will use a default one. 

Could you share you cypress configuration file or the whole project?

Also, it would be nice if you [collect the debug logs](https://github.com/mbolotov/intellij-cypress/issues/104#issuecomment-1247041722).

**Comment by arneevertsson** [comment]
Could I send the IntelliJ log through a private channel?

**Comment by mbolotov** [comment]
yep, you can send an email to mikhail.bolotov at Gmail
or use this slack channel https://join.slack.com/t/intellij-cypress/shared_invite/zt-g5lcy9xc-F3qy_g8O~qbZvKjD2m0EjQ

**Comment by andreikondratev** [comment]
Does not seem to pick up `*.cy.ts` files in IntelliJ IDEA 2022.3 (Ultimate Edition).

**Comment by mbolotov** [comment]
while I'm still searching for a way to evaluate a configuration with Cypress 11, you can use this bundle and disable config parsing: 
[Cypress Support Pro-3.5.1.zip](https://github.com/mbolotov/intellij-cypress/files/10141638/Cypress.Support.Pro-3.5.1.zip)

When disabled, a run configuration can be created from a gutter as usual, though some other features that depend on the data from config may not be available in this mode.

This mode is automatically enabled when Cypress 11 is detected:
![image](https://user-images.githubusercontent.com/19785715/205311364-5b1651ee-a8e3-45b6-8178-22b200959a8f.png)

**Comment by bajzik** [comment]
Hey guys, i have same problem with PHP Storm 2022.3 and Cypress 11. Is there workaround without Pro plugin?

**Comment by mbolotov** [comment]
@bajzik 
what do you mean by `workaround without Pro plugin`?
The `3.5.1` version should work with Cypress 11 (but with some limitation due to lack of the configuration data)

**Comment by bajzik** [comment]
3.5.1 is version of Pro plugin if I'm right, so also workaround above my comment is probably for Pro version. So I'm asking if there is workaround for free version.

**Comment by mbolotov** [comment]
What's the problem with the free version?
It doesn't use the configuration data so I expect there should be no problem regarding Cypress 11

**Comment by bajzik** [comment]
I dont have possibility to run .cy.ts test file nor any described test, or test case at all

![image](https://user-images.githubusercontent.com/20060144/206403735-4985156b-6428-4b4a-bdbc-1c3ff0322c9a.png)

**Comment by mbolotov** [comment]
So it was working okay with Cypress 10 and not working with Cypress 11?

**Comment by bajzik** [comment]
I better say with 9. I was updating Cypress from 9.5.* version to 11.

**Comment by mbolotov** [comment]
What's the name of your cypress configuration file?
It might be that the free version support only the default file names for a configuration file

**Comment by bajzik** [comment]
cypress.config.ts

**Comment by mbolotov** [comment]
could you share your project?
I've just checked my sample project and it works okay with the free version and Cypress 11.1.0

**Comment by bajzik** [comment]
Project is using yarn workspaces, where vue is one of package/ws and tests are another package/ws. So cypress.config.ts is in this test package where also test files (cy.ts) are stored.

**Comment by bajzik** [comment]
Nope, files are still the same. I think that we renamed test.ts co cy.ts but it was while ago. Is there any example for run configuration? Or it's not necessary if we're not able to run in from cy.ts file

**Comment by mbolotov** [comment]
anyway, I cannot reproduce the problem without a sample project

**Comment by list4c** [comment]
Hi there! 
https://github.com/bahmutov/fastify-example-tests
https://github.com/bahmutov/fastify-example
These are training materials from Gleb Bahmutov. Open source, there is a sample app and some spec files. I guess just using 
cy.visit('/') should be enough, as there is a baseUrl defined already.

I just tried to run a spec file after upgrading to Cypress 12 and it shows me a similar error:

```
it('shows the fruit returned from the test', () => {
^

ReferenceError: it is not defined
    at Object.<anonymous> (/home/mariusz/cypress-learner/network-requests-cypress-course/fastify-example-tests/cypress/e2e/spec03.cy.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.12.1

Process finished with exit code 1
```

**Comment by scmppmcs** [comment]
I have the same issue with phpstorm where I cannot run individual tests from within the test files.

here's a minimal reproducible example where I have this happening: https://github.com/scmppmcs/mre-cypress-phpstorm

my issue when accessing any test icon dropdown:
![image](https://user-images.githubusercontent.com/120712615/208061674-5460073c-bafd-4230-a1bd-3edc4d6e7813.png)

This is on an alma linux VM. This problem did not appear on other distro vms. Phpstorm is the snap version. One difference I saw with the other VM is that node is installed with snap but this one is not.

When I create a test configuration to run a single test within a test file then run it, I get this in logs with the relevant debug log setting (#me.mbolotov.cypress:all):

```
2022-12-16 09:55:48,869 [   7271] SEVERE - #c.i.u.c.QueueProcessor - PhpStorm 2022.3  Build #PS-223.7571.212
2022-12-16 09:55:48,870 [   7272] SEVERE - #c.i.u.c.QueueProcessor - JDK: 17.0.5; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2022-12-16 09:55:48,870 [   7272] SEVERE - #c.i.u.c.QueueProcessor - OS: Linux
2022-12-16 09:55:49,575 [   7977]   INFO - #c.j.r.f.FollowMeManager - Register new user 0:'admin' with ClientId=ClientId(value=Host)
2022-12-16 09:55:52,167 [  10569]   INFO - #c.i.o.w.i.GlobalMenuLinux - created instance of GlobalMenuLinux for xid=0x2000219
2022-12-16 09:55:52,287 [  10689]   INFO - #c.i.w.i.i.WorkspaceModelImpl - Load workspace model from cache in 98 ms
2022-12-16 09:55:52,301 [  10703]   INFO - #c.i.w.i.i.WorkspaceModelImpl - -------------------------------------------------------
2022-12-16 09:55:52,301 [  10703]   INFO - #c.i.w.i.i.WorkspaceModelImpl - Updating project model silently. Version before update 0.
2022-12-16 09:55:52,302 [  10704]   INFO - #c.i.w.i.i.WorkspaceModelImpl - Update description: Add module mapping
2022-12-16 09:55:52,302 [  10704]   INFO - #c.i.w.i.i.WorkspaceModelImpl - Update: 0 ms, To snapshot: 0 ms
2022-12-16 09:55:52,303 [  10705]   INFO - #c.i.w.i.i.WorkspaceModelImpl - -------------------------------------------------------
2022-12-16 09:55:52,323 [  10725]   WARN - #c.i.e.RunManager - Must be not called before project components initialized
2022-12-16 09:55:52,333 [  10735]   INFO - #c.i.o.v.i.p.NewMappings - VCS Root: [Git] - [/home/admin/Documents/test-cypress]
2022-12-16 09:55:52,335 [  10737]   INFO - #c.i.o.w.i.s.w.StatusBarWidgetsManager - Factory is not registered as `com.intellij.statusBarWidgetFactory` extension: com.intellij.openapi.vcs.changes.committed.IncomingChangesIndicatorFactory
2022-12-16 09:55:52,339 [  10741]   INFO - #c.j.r.p.c.t.i.DistributedTestHost - Host address=localhost/127.0.0.1
2022-12-16 09:55:52,343 [  10745]   INFO - #c.i.p.c.ProjectCodeStyleSettingsManager - Initialized from default code style settings.
2022-12-16 09:55:52,369 [  10771]   INFO - PerformancePlugin - Performance Plugin is in silent mode
2022-12-16 09:55:52,384 [  10786]   INFO - #c.i.i.n.e.NewToolbarRootPaneExtension - Show old main toolbar: false; show old navigation bar: true
2022-12-16 09:55:52,384 [  10786]   INFO - #c.i.i.n.e.NewToolbarRootPaneExtension - Show new main toolbar: false
2022-12-16 09:55:52,385 [  10787]   INFO - #c.i.o.w.i.s.w.StatusBarWidgetsManager - Factory is not registered as `com.intellij.statusBarWidgetFactory` extension: git4idea.ui.branch.GitBranchWidget$Factory
2022-12-16 09:55:52,562 [  10964]   INFO - #c.j.r.f.FollowMeManager - Register new user 0:'admin' with ClientId=ClientId(value=Host)
2022-12-16 09:55:52,844 [  11246]   WARN - #c.i.o.w.i.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix ToolWindow (ID:  Robo tasks) or icon RasterizedImageDataLoader(classLoader=PluginClassLoader(plugin=PluginDescriptor(name=PHP, id=com.jetbrains.php, descriptorPath=plugin.xml, path=/var/lib/snapd/snap/phpstorm/307/plugins/php-impl, version=223.7571.212, package=null, isBundled=true), packagePrefix=null, instanceId=131, state=active), path=icons/php-icon.svg)
2022-12-16 09:55:52,912 [  11314]   INFO - #c.i.u.i.UnindexedFilesScanner - Started scanning for indexing of test-cypress. Reason: On project open
2022-12-16 09:55:52,922 [  11324]   INFO - #c.i.u.i.UnindexedFilesScanner - Performing delayed pushing properties tasks for test-cypress took 10ms; general responsiveness: ok; EDT responsiveness: ok
2022-12-16 09:55:52,949 [  11351]   INFO - #c.j.p.t.PhpLocalTerminalCustomizer - Do not initialise terminal for null or remote sdk: null
2022-12-16 09:55:53,257 [  11659]   INFO - #c.i.o.e.s.p.m.ExternalProjectsDataStorage - Load external projects data in 0 millis (read time: 0)
2022-12-16 09:55:53,346 [  11748]   INFO - #c.i.i.s.p.i.SharedIndexChunkConfigurationImpl - Chunk bundled-js-predefined-ffdd448c697d-9b322a0dfcec-JavaScript-PS-223.7571.212 is registered for project 'test-cypress: matching: (fb=37, stub=86), incompatible: (fb=0, stub=0), unknown: (fb=9, stub=9), 
2022-12-16 09:55:53,578 [  11980]   INFO - #c.i.u.i.UnindexedFilesScanner - Scanning of test-cypress uses 11 scanning threads
2022-12-16 09:55:53,666 [  12068]   INFO - #c.i.d.u.SqlDialects - SQL dialects initialized in 32 ms
2022-12-16 09:55:53,742 [  12144]   INFO - #c.i.i.s.p.i.SharedIndexChunkConfigurationImpl - Chunk bundled-php-predefined-a9dfff28de4e-ee06eac2f0d2-com.jetbrains.php-PS-223.7571.212 is registered for project 'test-cypress: matching: (fb=88, stub=107), incompatible: (fb=0, stub=0), unknown: (fb=9, stub=9), 
2022-12-16 09:55:53,743 [  12145]   INFO - #c.i.i.s.p.i.BundledSharedIndexPostStartupActivity - Attached 2 pre-built shared indexes: bundled-js-predefined-ffdd448c697d-9b322a0dfcec-JavaScript-PS-223.7571.212, bundled-php-predefined-a9dfff28de4e-ee06eac2f0d2-com.jetbrains.php-PS-223.7571.212
2022-12-16 09:55:53,900 [  12302]   INFO - #c.i.w.i.i.WorkspaceModelImpl - Updating project model. New version: 2. Whole update took 18 ms. Desc: Node: update library entities
2022-12-16 09:55:53,959 [  12361]   INFO - #c.i.i.s.IdeStartupScripts - 0 startup script(s) found
2022-12-16 09:55:54,091 [  12493]   INFO - #c.i.d.PerformanceWatcherImpl - Post-startup activities under progress took 849ms; general responsiveness: ok; EDT responsiveness: ok
2022-12-16 09:55:54,515 [  12917]   INFO - #c.i.u.i.UnindexedFilesScanner - Scanning completed for test-cypress. Number of scanned files: 4539; Number of files for indexing: 0 took 1593ms; general responsiveness: ok; EDT responsiveness: ok
2022-12-16 09:55:54,516 [  12918]   INFO - #c.i.u.i.UnindexedFilesScanner - 93b2f50a: marking roots for initial VFS refresh
2022-12-16 09:55:54,520 [  12922]   INFO - #c.i.u.i.UnindexedFilesScanner - 93b2f50a: starting initial VFS refresh
2022-12-16 09:55:54,528 [  12930]   INFO - #c.i.u.i.UnindexedFilesScanner - Finished for test-cypress. No files to index with loading content.
2022-12-16 09:55:54,611 [  13013]   WARN - #c.i.u.x.Binding - no accessors for com.intellij.lang.annotation.HighlightSeverity
2022-12-16 09:55:55,097 [  13499]   INFO - #c.i.u.i.UnindexedFilesScanner - 93b2f50a: initial VFS refresh finished 575 ms
2022-12-16 09:55:58,569 [  16971]   INFO - #c.i.o.a.i.PopupMenuPreloader - 6066 ms since showing to preload popup menu 'File' at 'MainMenu(preload-bgt)' in 131 ms
2022-12-16 09:55:58,591 [  16993]   INFO - #c.i.o.a.i.PopupMenuPreloader - 6094 ms since showing to preload popup menu 'View' at 'MainMenu(preload-bgt)' in 154 ms
2022-12-16 09:55:58,599 [  17001]   INFO - #c.i.o.a.i.PopupMenuPreloader - 6103 ms since showing to preload popup menu 'Edit' at 'MainMenu(preload-bgt)' in 163 ms
2022-12-16 09:55:58,639 [  17041]   INFO - #c.i.o.a.i.PopupMenuPreloader - 6142 ms since showing to preload popup menu 'Navigate' at 'MainMenu(preload-bgt)' in 201 ms
2022-12-16 09:55:58,659 [  17061]   INFO - #c.i.o.a.i.PopupMenuPreloader - 6163 ms since showing to preload popup menu 'Code' at 'MainMenu(preload-bgt)' in 222 ms
2022-12-16 09:55:58,709 [  17111]   INFO - #c.i.u.t.DateFormatUtil - cannot load system formats (JNA=true), resorting to JRE for en_US
2022-12-16 09:55:58,724 [  17126]   INFO - #c.i.o.a.i.PopupMenuPreloader - 6227 ms since showing to preload popup menu 'Run' at 'MainMenu(preload-bgt)' in 286 ms
2022-12-16 09:55:58,726 [  17128]   INFO - #c.i.o.a.i.PopupMenuPreloader - 6229 ms since showing to preload popup menu 'Refactor' at 'MainMenu(preload-bgt)' in 288 ms
2022-12-16 09:55:58,734 [  17136]   INFO - #c.i.o.a.i.PopupMenuPreloader - 6238 ms since showing to preload popup menu 'Window' at 'MainMenu(preload-bgt)' in 296 ms
2022-12-16 09:55:58,794 [  17196]   INFO - #c.i.o.a.i.PopupMenuPreloader - 6297 ms since showing to preload popup menu 'Tools' at 'MainMenu(preload-bgt)' in 356 ms
2022-12-16 09:55:58,814 [  17216]   INFO - #c.i.o.a.i.PopupMenuPreloader - 6317 ms since showing to preload popup menu 'Help' at 'MainMenu(preload-bgt)' in 376 ms
2022-12-16 09:55:58,954 [  17356]   INFO - #c.i.o.a.i.PopupMenuPreloader - 6024 ms since showing to preload popup menu 'Project View Popup Menu' at 'ProjectViewPopup(preload-bgt)' in 512 ms
2022-12-16 09:55:59,049 [  17451]   INFO - #c.i.o.a.i.PopupMenuPreloader - 5901 ms since showing to preload popup menu 'Editor Popup Menu' at 'EditorPopup(preload-bgt)' in 606 ms
2022-12-16 09:55:59,052 [  17454]   INFO - #c.i.o.a.i.PopupMenuPreloader - 5847 ms since showing to preload popup menu 'Editor Popup Menu' at 'EditorPopup(preload-bgt)' in 609 ms
2022-12-16 09:55:59,143 [  17545]   INFO - #c.j.r.p.c.CodeWithMeCleanup - running activity to cleanup old thin clients... Root path is '/home/admin/.cache/JetBrains'. JvmStartTimeMs=1671180941308
2022-12-16 09:55:59,145 [  17547]   INFO - #c.j.r.p.c.CodeWithMeCleanup - found 0 Code With Me client system folders to check
2022-12-16 09:55:59,146 [  17548]   INFO - #c.j.r.p.c.CodeWithMeCleanup - found 0 Code With Me client config folders to check
2022-12-16 09:55:59,148 [  17550]   INFO - #c.j.r.p.c.CodeWithMeCleanup - keep only [] major versions
2022-12-16 09:55:59,181 [  17583]   INFO - #c.i.w.i.i.WorkspaceModelImpl - Updating project model. New version: 3. Whole update took 5 ms. Desc: Apply JPS storage (iml files)
2022-12-16 09:55:59,183 [  17585]   INFO - #c.i.w.i.i.j.s.DelayedProjectSynchronizer$Companion - Workspace model loaded from cache. Syncing real project state into workspace model in 73 ms. Thread[DefaultDispatcher-worker-44,5,main]
2022-12-16 09:55:59,494 [  17896]   INFO - #c.i.j.n.p.n.PackageVersionRangeMatcher - Matching 6 done in 53 ms
2022-12-16 09:55:59,958 [  18360]   INFO - #c.i.v.l.d.VcsLogData - Username not configured for root file:///home/admin/Documents/test-cypress
2022-12-16 09:56:00,052 [  18454]   INFO - #c.i.v.l.d.i.VcsLogPersistentIndex - Indexing 1 commits in test-cypress
2022-12-16 09:56:00,101 [  18503]   INFO - #c.i.v.l.d.i.VcsLogPersistentIndex - 44ms for indexing 1 new commits out of 1 in test-cypress
2022-12-16 09:56:00,111 [  18513]   INFO - #c.i.v.l.d.i.VcsLogPersistentIndex - Indexing 1 commits in test-cypress
2022-12-16 09:56:00,112 [  18514]   INFO - #c.i.v.l.d.i.IndexDiagnosticRunner - Running index diagnostic for [file:///home/admin/Documents/test-cypress]
2022-12-16 09:56:00,114 [  18516]   INFO - #c.i.v.l.d.i.VcsLogPersistentIndex - 3ms for indexing 0 new commits out of 1 in test-cypress
2022-12-16 09:56:21,038 [  39440]   INFO - #c.i.c.ComponentStoreImpl - Saving appFileTypeManager took 12 ms
2022-12-16 09:56:21,194 [  39596]   INFO - #c.i.c.ComponentStoreImpl - Saving Project(name=test-cypress, containerState=COMPONENT_CREATED, componentStore=/home/admin/Documents/test-cypress)PHPCSFixerOptionsConfiguration took 14 ms, RunManager took 46 ms
2022-12-16 09:57:28,646 [ 107048]   INFO - #c.i.c.ComponentStoreImpl - Saving Project(name=test-cypress, containerState=COMPONENT_CREATED, componentStore=/home/admin/Documents/test-cypress)RunManager took 13 ms
2022-12-16 10:00:54,744 [ 313146]   INFO - #c.i.i.b.BookmarkManager - no state loaded for old bookmarks
2022-12-16 10:00:54,765 [ 313167]   INFO - #c.i.i.f.FavoritesManager - no state loaded for old favorites
2022-12-16 10:02:46,005 [ 424407] SEVERE - #me.mbolotov.cypress.run.CypressRunState - Failed to run Cypress configuration
com.intellij.execution.ExecutionException: Unable to add a .only keyword to run a single test
	at me.mbolotov.cypress.run.CypressRunState.onlyfiOrDie(CypressRunState.kt:210)
	at me.mbolotov.cypress.run.CypressRunState.configureCommandLine(CypressRunState.kt:186)
	at me.mbolotov.cypress.run.CypressRunState.execute(CypressRunState.kt:61)
	at com.intellij.execution.runners.DefaultRunProgramRunner$execute$1.invoke(DefaultRunProgramRunner.kt:29)
	at com.intellij.execution.runners.DefaultRunProgramRunner$execute$1.invoke(DefaultRunProgramRunner.kt:18)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:173)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:171)
	at com.intellij.execution.impl.ExecutionManagerImpl.doStartRunProfile$lambda-3(ExecutionManagerImpl.kt:234)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:429)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:74)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:114)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:36)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:774)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
2022-12-16 10:02:46,007 [ 424409] SEVERE - #me.mbolotov.cypress.run.CypressRunState - PhpStorm 2022.3  Build #PS-223.7571.212
2022-12-16 10:02:46,007 [ 424409] SEVERE - #me.mbolotov.cypress.run.CypressRunState - JDK: 17.0.5; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2022-12-16 10:02:46,007 [ 424409] SEVERE - #me.mbolotov.cypress.run.CypressRunState - OS: Linux
2022-12-16 10:02:46,007 [ 424409] SEVERE - #me.mbolotov.cypress.run.CypressRunState - Plugin to blame: Cypress Support version: 1.4.3
2022-12-16 10:02:46,021 [ 424423]   INFO - #c.i.e.r.ExecutionUtil - Error running 'specific test':<br>Unable to add a .only keyword to run a single test
com.intellij.execution.ExecutionException: Unable to add a .only keyword to run a single test
	at me.mbolotov.cypress.run.CypressRunState.onlyfiOrDie(CypressRunState.kt:210)
	at me.mbolotov.cypress.run.CypressRunState.configureCommandLine(CypressRunState.kt:186)
	at me.mbolotov.cypress.run.CypressRunState.execute(CypressRunState.kt:61)
	at com.intellij.execution.runners.DefaultRunProgramRunner$execute$1.invoke(DefaultRunProgramRunner.kt:29)
	at com.intellij.execution.runners.DefaultRunProgramRunner$execute$1.invoke(DefaultRunProgramRunner.kt:18)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:173)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:171)
	at com.intellij.execution.impl.ExecutionManagerImpl.doStartRunProfile$lambda-3(ExecutionManagerImpl.kt:234)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:429)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:74)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:114)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:36)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:774)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

If you have any suggestions on additional steps to debug this, please tell!

**Comment by mbolotov** [comment]
hi @scmppmcs! 
Could you try this bundle 
[Cypress Support-1.5.1-DEBUG.zip](https://github.com/mbolotov/intellij-cypress/files/10347289/Cypress.Support-1.5.1-DEBUG.zip) and post the new log?
I've added some additional logging there.

**Comment by mbolotov** [comment]
hi @list4c!
Are you able to run the tests from the command line?
I was unable to reproduce the problem either way.

**Comment by mbolotov** [comment]
Cypresso plugin version 1.8.0 is able to evaluate Cypress configuration for 11+ version.
So this problem should go away.
