### ISSUE TITLE
Looks like the plugin is not playing well with some part of IntelliJ's API

### ISSUE THREAD

**Issue by kkoster** [mbolotov/intellij-cypress#111]
Reported by IntelliJ on IDE Internal Errors: 
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
	at com.intellij.openapi.project.IndexNotReadyException.create(IndexNotReadyException.java:67)
	at com.intellij.util.indexing.FileBasedIndexImpl.handleDumbMode(FileBasedIndexImpl.java:844)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:792)
	at com.intellij.psi.stubs.StubIndexEx.getContainingIds(StubIndexEx.java:350)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:157)
	at com.intellij.psi.stubs.StubIndex.processElements(StubIndex.java:50)
	at com.intellij.lang.typescript.resolve.TypeScriptClassResolver.processGlobalElementsByQName(TypeScriptClassResolver.java:177)
	at com.intellij.lang.typescript.resolve.TypeScriptClassResolver.findGlobalElementsByQName(TypeScriptClassResolver.java:159)
	at com.intellij.lang.typescript.resolve.TypeScriptClassResolver.findGlobalElementsByQName(TypeScriptClassResolver.java:141)
	at com.intellij.lang.typescript.TypeScriptResolveHelper.processGlobalThings(TypeScriptResolveHelper.java:120)
	at com.intellij.lang.javascript.psi.resolve.JSReferenceExpressionResolver.processGlobalDeclarations(JSReferenceExpressionResolver.java:219)
	at com.intellij.lang.javascript.psi.resolve.JSReferenceExpressionResolver.doResolveGlobalReference(JSReferenceExpressionResolver.java:204)
	at com.intellij.lang.javascript.psi.resolve.JSReferenceExpressionResolver.resolveGlobalReference(JSReferenceExpressionResolver.java:192)
	at com.intellij.lang.javascript.psi.resolve.JSReferenceExpressionResolver.resolve(JSReferenceExpressionResolver.java:104)
	at com.intellij.lang.javascript.psi.resolve.JSReferenceExpressionResolver.resolve(JSReferenceExpressionResolver.java:39)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil$5.get(JSResolveUtil.java:1638)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil$5.get(JSResolveUtil.java:1635)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluatorComplexityTracker.runTask(JSEvaluatorComplexityTracker.java:72)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard.lambda$getCachedValue$0(JSComplexityAwareRecursionGuard.java:71)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil$4.lambda$calculateWithCaching$0(JSResolveUtil.java:1651)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:289)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil$4.calculateWithCaching(JSResolveUtil.java:1649)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard.getCachedValue(JSComplexityAwareRecursionGuard.java:74)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil.resolve(JSResolveUtil.java:1633)
	at com.intellij.lang.javascript.psi.impl.JSReferenceExpressionImpl.multiResolve(JSReferenceExpressionImpl.java:527)
	at com.intellij.lang.javascript.psi.types.evaluable.JSReferenceExpressionType.getResolveResultsFromQualifier(JSReferenceExpressionType.java:134)
	at com.intellij.lang.javascript.psi.types.evaluable.JSReferenceExpressionType.evaluate(JSReferenceExpressionType.java:80)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.processRefExpr(JSTypeEvaluator.java:1034)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.doEvaluateTypesImpl(JSTypeEvaluator.java:251)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.doEvaluateTypes(JSTypeEvaluator.java:223)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.doEvaluateExpressionOrElementTypes(JSTypeEvaluator.java:121)
	at com.intellij.lang.javascript.psi.types.JSPsiBasedTypeOfType.evaluate(JSPsiBasedTypeOfType.java:111)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluableTypeResolver.lambda$doUnwrapRecursivelyInternal$2(JSEvaluableTypeResolver.java:108)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard.doPreventingRecursion(JSComplexityAwareRecursionGuard.java:94)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluationRecursionGuard.compute(JSEvaluationRecursionGuard.java:36)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluableTypeResolver.doUnwrapRecursivelyInternal(JSEvaluableTypeResolver.java:108)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluableTypeResolver.doUnwrapRecursively(JSEvaluableTypeResolver.java:86)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluableTypeResolver.unwrapRecursively(JSEvaluableTypeResolver.java:76)
	at com.intellij.lang.javascript.psi.resolve.JSCompleteTypeEvaluationProcessor.process(JSCompleteTypeEvaluationProcessor.java:33)
	at com.intellij.lang.javascript.psi.resolve.JSCompleteTypeEvaluationProcessor.evaluateTypes(JSCompleteTypeEvaluationProcessor.java:124)
	at com.intellij.lang.javascript.psi.resolve.QualifiedItemProcessor.evaluateExpressionOrElementType(QualifiedItemProcessor.java:628)
	at com.intellij.lang.javascript.psi.resolve.JSReferenceExpressionResolver.resolve(JSReferenceExpressionResolver.java:118)
	at com.intellij.lang.javascript.psi.resolve.JSReferenceExpressionResolver.resolve(JSReferenceExpressionResolver.java:39)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil$5.get(JSResolveUtil.java:1638)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil$5.get(JSResolveUtil.java:1635)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluatorComplexityTracker.runTask(JSEvaluatorComplexityTracker.java:72)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard.lambda$getCachedValue$0(JSComplexityAwareRecursionGuard.java:71)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil$4.lambda$calculateWithCaching$0(JSResolveUtil.java:1651)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:289)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil$4.calculateWithCaching(JSResolveUtil.java:1649)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard.getCachedValue(JSComplexityAwareRecursionGuard.java:74)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil.resolve(JSResolveUtil.java:1633)
	at com.intellij.lang.javascript.psi.impl.JSReferenceExpressionImpl.multiResolve(JSReferenceExpressionImpl.java:527)
	at com.intellij.lang.javascript.psi.types.evaluable.JSReferenceExpressionType.getResolveResultsFromQualifier(JSReferenceExpressionType.java:134)
	at com.intellij.lang.javascript.psi.types.evaluable.JSReferenceExpressionType.evaluate(JSReferenceExpressionType.java:80)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.processRefExpr(JSTypeEvaluator.java:1034)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.doEvaluateTypesImpl(JSTypeEvaluator.java:251)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.doEvaluateTypes(JSTypeEvaluator.java:223)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.doEvaluateExpressionOrElementTypes(JSTypeEvaluator.java:121)
	at com.intellij.lang.javascript.psi.types.JSPsiBasedTypeOfType.evaluate(JSPsiBasedTypeOfType.java:111)
	at com.intellij.lang.javascript.psi.types.evaluable.JSTypeStructuralPartEvaluator.evaluate(JSTypeStructuralPartEvaluator.java:32)
	at com.intellij.lang.javascript.psi.types.evaluable.JSApplyCallType.evaluate(JSApplyCallType.java:163)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluableTypeResolver.lambda$doUnwrapRecursivelyInternal$2(JSEvaluableTypeResolver.java:108)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard.doPreventingRecursion(JSComplexityAwareRecursionGuard.java:94)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluationRecursionGuard.compute(JSEvaluationRecursionGuard.java:36)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluableTypeResolver.doUnwrapRecursivelyInternal(JSEvaluableTypeResolver.java:108)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluableTypeResolver.doUnwrapRecursively(JSEvaluableTypeResolver.java:86)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluableTypeResolver.unwrapRecursively(JSEvaluableTypeResolver.java:76)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluableTypeResolver.lambda$doUnwrapRecursivelyInternal$3(JSEvaluableTypeResolver.java:115)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard.doPreventingRecursion(JSComplexityAwareRecursionGuard.java:94)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluationRecursionGuard.compute(JSEvaluationRecursionGuard.java:36)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluableTypeResolver.lambda$doUnwrapRecursivelyInternal$4(JSEvaluableTypeResolver.java:114)
	at com.intellij.lang.javascript.psi.resolve.complexity.JSEvaluationResultElement.transform(JSEvaluationResultElement.java:85)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluableTypeResolver.doUnwrapRecursivelyInternal(JSEvaluableTypeResolver.java:110)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluableTypeResolver.doUnwrapRecursively(JSEvaluableTypeResolver.java:86)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluationCache$CacheProviderExpressionType.apply(JSEvaluationCache.java:26)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluationCache.lambda$doGetElementType$2(JSEvaluationCache.java:61)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard$1.lambda$get$0(JSComplexityAwareRecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard.doPreventingRecursion(JSComplexityAwareRecursionGuard.java:94)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard$1.get(JSComplexityAwareRecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluatorComplexityTracker.runTask(JSEvaluatorComplexityTracker.java:72)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard.getCachedValue(JSComplexityAwareRecursionGuard.java:40)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluationCache.doGetElementType(JSEvaluationCache.java:53)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluationCache.getElementType(JSEvaluationCache.java:47)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.getElementType(JSTypeEvaluator.java:150)
	at me.mbolotov.cypress.lang.InjectKt.A(Unknown Source)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:149)
	at me.mbolotov.cypress.lang.InjectKt.evalType(Unknown Source)
	at me.mbolotov.cypress.lang.InjectKt.isOfChainableType(Unknown Source)
	at me.mbolotov.cypress.lang.InjectKt.isOfChainableType$default(Unknown Source)
	at me.mbolotov.cypress.completion.CyCompletionContributorKt.isCyGetSelector(Unknown Source)
	at me.mbolotov.cypress.run.CyDebugSessionManager.A(Unknown Source)
	at com.intellij.psi.impl.PsiDocumentManagerBase.performForCommittedDocument(PsiDocumentManagerBase.java:268)
	at me.mbolotov.cypress.run.CyDebugSessionManager.updatePosition(Unknown Source)
	at me.mbolotov.cypress.run.CyDebugSessionManager$_B$1.mouseMoved(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor255.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:120)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:85)
	at jdk.proxy1/jdk.proxy1.$Proxy110.mouseMoved(Unknown Source)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseMotionListener.mouseMoved(EditorImpl.java:4479)
	at java.desktop/java.awt.Component.processMouseMotionEvent(Component.java:6693)
	at java.desktop/javax.swing.JComponent.processMouseMotionEvent(JComponent.java:3410)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4588)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:840)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Versions**:
- Plugin: Cypress Support Pro 3.5
- IDE: IntelliJ Ultimate 2022.2.3 Build 222.4345.14
- OS: Windows 10 Pro (latest patches applied)

**Comment by mbolotov** [comment]
should be fixed in `3.5.1` version
