### ISSUE TITLE
Cannot find module 'npx-cli.js

### ISSUE THREAD

**Issue by robfreundlich** [mbolotov/intellij-cypress#6]
When i try to run a test (Right-click -> Run test -> Cypress Run), it crashes immediately with the following output:
```
$PATH_TO_NODE\node.exe $PATH_TO_NODE\node_modules\npm\bin\npx-cli.js cypress run --reporter $PATH_TO_TEST_DIR/node_modules/cypress-intellij-reporter --spec $PATH_TO_TEST_DIR/cypress/path/to/MyTestSpec.spec.ts
module.js:472
    throw err;
    ^

Error: Cannot find module '$PATH_TO_NODE\node_modules\npm\bin\npx-cli.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3

Process finished with exit code 1
```

**Comment by mbolotov** [comment]
Hi Rob!
Is this issue still actual for you?

**Comment by robfreundlich** [comment]
Nope, it's working fine now.
