### ISSUE TITLE
Unable to add a .only keyword to run a single test

### ISSUE THREAD

**Issue by dzmitry-kakaruk-webjet** [mbolotov/intellij-cypress#61]
Failed to run Cypress configuration

com.intellij.execution.ExecutionException: Unable to add a .only keyword to run a single test
	at me.mbolotov.cypress.run.CypressRunState$JsOnlifier.onlyfiSpec(Unknown Source)
	at me.mbolotov.cypress.run.CypressRunState.A(Unknown Source)
	at me.mbolotov.cypress.run.CypressRunState.execute(Unknown Source)
	at me.mbolotov.cypress.run.CypressRunState.execute(Unknown Source)
	at com.intellij.execution.runners.DefaultRunProgramRunner$execute$1.invoke(DefaultRunProgramRunner.kt:21)
	at com.intellij.execution.runners.DefaultRunProgramRunner$execute$1.invoke(DefaultRunProgramRunner.kt:12)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:171)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:70)
	at com.intellij.execution.impl.ExecutionManagerImpl$doStartRunProfile$startRunnable$1.run(ExecutionManagerImpl.kt:232)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:886)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:755)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:441)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:487)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by mbolotov** [comment]
closing as no feedback received.
feel free to comment/create a new issue if problem persists

**Comment by dzmitry-kakaruk-webjet** [comment]
Oh, sorry. I missed this. All good, it works as expected now

**Comment by Ethan-G** [comment]
I'm getting this on WebStorm 2022.2.3. The run config seems right, not sure what else to check. I'm confused by the "check if the problem persists in 2.4.0" given the latest version seems to be 1.4.3.

**Comment by mbolotov** [comment]
`2.4.0` was about the Cypress Support *Pro* version. 
Do you get this error stably?
Can you provide the stack trace?

**Comment by Ethan-G** [comment]
Ah right thanks for clearing up the version confusion. Yes it occurs every time I try to execute the run configuration.

Stacktrace:

```
Failed to run Cypress configuration

com.intellij.execution.ExecutionException: Unable to add a .only keyword to run a single test
	at me.mbolotov.cypress.run.CypressRunState.onlyfiOrDie(CypressRunState.kt:210)
	at me.mbolotov.cypress.run.CypressRunState.configureCommandLine(CypressRunState.kt:186)
	at me.mbolotov.cypress.run.CypressRunState.execute(CypressRunState.kt:61)
	at com.intellij.execution.runners.DefaultRunProgramRunner$execute$1.invoke(DefaultRunProgramRunner.kt:29)
	at com.intellij.execution.runners.DefaultRunProgramRunner$execute$1.invoke(DefaultRunProgramRunner.kt:12)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:173)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:72)
	at com.intellij.execution.impl.ExecutionManagerImpl$doStartRunProfile$startRunnable$1.run(ExecutionManagerImpl.kt:234)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

Cheers

**Comment by PhilippeRT** [comment]
Hello,

I've got the same issue with the same versions : Webstorm 2.2.3 and plugin 1.4.3.
Have you got a solution ?

Thanks.

**Comment by jippeholwerda** [comment]
Same problem here. The first testrun of a single test is ok. Afterwards, the ".only" keyword is not removed. If I run the test again I get the error below. If I manually remove the ".only" keyword it runs fine.

Stacktrace:

```
Failed to run Cypress configuration

com.intellij.execution.ExecutionException: Unable to add a .only keyword to run a single test
	at me.mbolotov.cypress.run.CypressRunState.onlyfiOrDie(CypressRunState.kt:240)
	at me.mbolotov.cypress.run.CypressRunState.configureCommandLine(CypressRunState.kt:215)
	at me.mbolotov.cypress.run.CypressRunState.execute(CypressRunState.kt:76)
	at com.intellij.execution.runners.DefaultRunProgramRunner$execute$1.invoke(DefaultRunProgramRunner.kt:29)
	at com.intellij.execution.runners.DefaultRunProgramRunner$execute$1.invoke(DefaultRunProgramRunner.kt:18)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:173)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:171)
	at com.intellij.execution.impl.ExecutionManagerImpl.doStartRunProfile$lambda$2(ExecutionManagerImpl.kt:234)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:429)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:74)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:114)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:36)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:772)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

**Comment by nkamp** [comment]
And I get this error as well:
I have the webstorm Ultimate version : 2025.1.7 and Cypress 15.7.1
I have three tests in an <test_name>.spec.ts file and I have had the it.only(...) for one test. But I have replaced it with 'it(...)'. 

Ah, I see now the message of "[jippeholwerda](https://github.com/jippeholwerda)
[on Jan 27, 2023](https://github.com/mbolotov/intellij-cypress/issues/61#issuecomment-1406429072)"

**He was nearly three years ago working on this project and it seems that it is still not solved?** Or did I missed something?

I have made also a new "cypress" project in webstorm with example code, the same issue? And it seems that if disable the plugin cypresso, I can't run these tests either, the same error?


> Failed to run Cypress configuration
> 
> com.intellij.execution.ExecutionException: Unable to add a .only keyword to run a single test
> 	at me.mbolotov.cypress.run.s.a(SourceFile:399)
> 	at me.mbolotov.cypress.run.j.execute(SourceFile:2267)
> 	at me.mbolotov.cypress.run.j.execute(SourceFile:91)
> 	at com.intellij.javascript.debugger.execution.DebuggableProgramRunnerKt.doExecuteDebuggableProgram$lambda$3(DebuggableProgramRunner.kt:60)
> 	at com.intellij.javascript.debugger.execution.DebuggableProgramRunnerKt.doExecuteDebuggableProgram$lambda$4(DebuggableProgramRunner.kt:54)
> 	at org.jetbrains.concurrency.DonePromise.thenAsync(promise.kt:526)
> 	at com.intellij.javascript.debugger.execution.DebuggableProgramRunnerKt.doExecuteDebuggableProgram(DebuggableProgramRunner.kt:54)
> 	at com.intellij.javascript.debugger.execution.DebuggableProgramRunnerKt.access$doExecuteDebuggableProgram(DebuggableProgramRunner.kt:1)
> 	at com.intellij.javascript.debugger.execution.DebuggableProgramRunner.execute(DebuggableProgramRunner.kt:31)
> 	at com.intellij.execution.runners.AsyncProgramRunner.execute$lambda$0(GenericProgramRunner.kt:53)
> 	at com.intellij.execution.impl.ExecutionManagerImpl.startRunProfile$lambda$5(ExecutionManagerImpl.kt:228)
> 	at com.intellij.execution.impl.ExecutionManagerImpl$doStartRunProfile$$inlined$Runnable$1.run(Runnable.kt:30)
> 	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:240)
> 	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:25)
> 	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:202)
> 	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread$lambda$7(AnyThreadWriteThreadingSupport.kt:319)
> 	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction$lambda$6(AnyThreadWriteThreadingSupport.kt:274)
> 	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWithTemporaryThreadLocal(AnyThreadWriteThreadingSupport.kt:204)
> 	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:274)
> 	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:222)
> 	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread(AnyThreadWriteThreadingSupport.kt:318)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:928)
> 	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:501)
> 	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:102)
> 	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:102)
> 	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:108)
> 	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:102)
> 	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
> 	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:117)
> 	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:43)
> 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
> 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:585)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:482)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$12$lambda$11$lambda$10$lambda$9(IdeEventQueue.kt:307)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:864)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$12$lambda$11$lambda$10(IdeEventQueue.kt:306)
> 	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$3(IdeEventQueue.kt:958)
> 	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:109)
> 	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:958)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$12(IdeEventQueue.kt:301)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:341)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
> 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
>

**Comment by mbolotov** [comment]
should be fixed in 2.2.0 version

**Comment by nkamp** [comment]
I've installed it in Webstorm. I have followed the youtube [video](https://www.youtube.com/watch?v=r60vOKkY8m4).

My test <file_name>spec.ts :
`describe("My test description", function () {
  context("context description", function () {
    it.only("This is the test for debugging", function () {...})`


When I fill the cypress configuration according to the video (Cypress Interactive Debugger):

- check: Interactive mode
- select: Electron
-  Program arguments: -b electron
- Cypress project base... : C:\users\...\....\frontend
- Environment variables: 
- Test file: ~\...\....\frontend\tests\e2e\....\<file_name>spec.ts
- Test name: This is the test for debugging
- check: Test

But I get the error "! Error: Unable to find the specified test to run".

Our test files don't have '.cy' in the name. I have changed the file name to: '<file_name>spec.cy.ts', but with the same error.

I just discovered another thing. 
When I start the test from the "side bar"(next to the line numbers) with 'Debug ...' , than I see in the debug console the message: Error: Unexpected major version of webpack-dev-server. Cypress webpack-dev-server works with webpack-dev-server versions 5 - saw 4.15.2.
This is transistive dependency.
I've installed 'webpack-dev-server' as top-level dependency.

Now I do get the message: "Cannot find package '@/base' imported from...". I can't find the dependency '@base'. 
I have installed the dependency base, I do not find the package @base as mentioned in the error message. 
I get still the same error message: "Cannot find package '@/base' imported from...".

**Another questions:** 
- Next to the missing packages, must there be an property in the cypress.config.ts file?
- And if I look to the video, than it is working headless. But can this also run headed in the browser so that I can follow it? Than browser must be connected with webstorm of course.
- And are there consequences if we swith to Vite? Because 'vue-cli' is deprecated\maintenance mode. And when gone use vite, than I think we can\will remove the webpack\webpack-dev-server?

**Comment by mbolotov** [comment]
Hi @nkamp,

1. how do you create a run configuration when you are getting "! Error: Unable to find the specified test to run" message? 
2. do you get the same `webpack-dev-server`/`@base` errors when you start the test by `Run` option or directly by Cypress in the command line?
3. in the video, it starts the Cypress in the *headed* mode, not in headless. You can notice that there is neither `headless` option checked in the run configuration, nor `--headless` flag shown in the command line when it started. Also, what do you mean by 'browser must be connected to webstorm'?
4. there is no known problems with Vite, you could try
