### ISSUE TITLE
me.mbolotov.cypress.run.ShowCypressScreenshotAction' is already taken by action 'Show Cypress Screenshot

### ISSUE THREAD

**Issue by paul9115** [mbolotov/intellij-cypress#93]
The error seems to be triggered whenever PhpStorm is launched. 
```
com.intellij.diagnostic.PluginException: ID 'me.mbolotov.cypress.run.ShowCypressScreenshotAction' is already taken by action 'Show Cypress Screenshot (Open Cypress screenshot for an executed test)' (class com.intellij.openapi.actionSystem.impl.ChameleonAction)  (Plugin: Cypress Support Pro). Action 'Show Cypress Screenshot (Open Cypress screenshot for an executed test)' (class com.intellij.openapi.actionSystem.ActionStub) cannot use the same ID me.mbolotov.cypress [Plugin: me.mbolotov.cypress]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionIdCollision(ActionManagerImpl.java:1330)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerAction(ActionManagerImpl.java:1264)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerOrReplaceActionInner(ActionManagerImpl.java:718)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.processActionElement(ActionManagerImpl.java:688)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerPluginActions(ActionManagerImpl.java:485)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerActions(ActionManagerImpl.java:169)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.<init>(ActionManagerImpl.java:141)
	at com.jetbrains.rdserver.ui.actionPopupMenu.BackendActionManager.<init>(BackendActionManager.kt:17)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:47)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:891)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:51)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:41)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:119)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:73)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:66)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:610)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:584)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.intellij.openapi.actionSystem.ActionManager.getInstance(ActionManager.java:29)
	at com.intellij.openapi.actionSystem.ex.ActionManagerEx.getInstanceEx(ActionManagerEx.java:20)
	at com.intellij.openapi.actionSystem.ex.ActionManagerEx.lambda$doWithLazyActionManager$1(ActionManagerEx.java:110)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by mbolotov** [comment]
hi @paul9115!
Are you still suffering from this issue?
It can probably happen if you didn't uninstall a previous version of either `Cypress Support` or `Cypress Support Pro` plugin . before installing a new one.

**Comment by paul9115** [comment]
I still see this now and again, plugin was on a fresh OS installation so no old versions laying around as far as I'm aware. I'll give it an uninstall/reinstall and monitor it for a few days

**Comment by paul9115** [comment]
@mbolotov 
I have removed and reinstalled the plugin and am still seeing the same issue. I don't see any previous plugins and `Cypress Support` is not installed either.

**Comment by mbolotov** [comment]
Hey, I've looked at the logs more precisely. 
They show you do have the both `free` and `Pro` version installed:

> (Plugin: **Cypress Support Pro**). Action 'Show Cypress Screenshot (Open Cypress screenshot for an executed test)' (class com.intellij.openapi.actionSystem.ActionStub) cannot use the same ID me.mbolotov.cypress [Plugin: **me.mbolotov.cypress**]

The `me.mbolotov.cypress` id is for the `base` version. 

So there nothing can be fixed in this case.
